sudo: false
language: node_js
cache:
  directories:
    - ~/.npm
install: true

jobs:
  include:
    - stage: test and deploy
      node_js: '10'
      if: branch = master AND tag IS blank
      script:
        - npm install
        - npm run lint
        - npm run ava
        - npm run travis-deploy-once "npm run semantic-release"
    - stage: docker release
      node_js: '10'
      if: tag IS present
      script:
        - docker build -t <%- docker %> .
        - docker tag <%- docker %> <%- docker %>:$TRAVIS_TAG
        - docker images
        - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
        - docker push <%- docker %>:latest;
        - docker push <%- docker %>:$TRAVIS_TAG;
